language: go

branches:
  only:
  - master
  - develop
  - staging

services:
  - docker

addons:
  hosts:
    - node-1
    - node-2
    - node-3
    - node-4
    - node-5
    - node-6

install:
  - ". $HOME/.nvm/nvm.sh"
  - nvm install stable
  - nvm use stable
  - npm install

script:
  - make docker_image && ./test/integration/test.sh

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      make push_image ;
    else
      TAG=$TRAVIS_BRANCH make push_tag_image ;
    fi

after_failure:
  - if [[ "$TRAVIS_BRANCH" == "develop" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      TAG=$TRAVIS_BRANCH make push_tag_image ;
    fi
  - curl -i "http://localhost:46657/dump_consensus_state"
  - cd ~/volumes/testnet/travis/scripts && docker-compose logs -t

before_deploy:
  - BUILD_TAG=$TRAVIS_TAG make dist
  - export RELEASE_PKG_FILE=$(ls build/dist/*.zip)

deploy:
  provider: releases
  overwrite: true
  api-key:
    secure: iIaBQLDBPzi95sIt36XaOaSrD7hwB/dUxAfpCeFLoFqdGNsGZhaPp4XfW8UghwqNlUF9spW1Ri8uOMF2Ig3FBTmeL/GELJl8pSJwhjb3Ra3p+kGg5eKyIZMvK1m9uoXBBMlMnjPhS9h0Z8bOpXLiEpQASV6nnJ0KE2N39ff3jBKShWDNWejOAYBTNNJ9N7GF8gh6z/xLwZ82nLWmOYGkwrEA9fH93IzguehmUyD2bbU66un0QrRfUCQ8xruxTENZ9ATz7GqOrqYe0L+IUbmK10VIYlJ1S7PcWvBSY4J4nslLnpFw2m+/3Zt2Cq/xaCLs7bmOlMie0AEbtyGamXxEIlNcIeWeOIyXv0k4yqGm5+IUl2scggDXGmysXCjwbQbLnPbHXo0sYlNMUr4WkH2LlPENT9r4mQGDwOYkrwt0ZlU9n+67IpgTBuBqd//khzmnjdDPleWZyr6fOfjfA8uBGbcO8fANyJOAzoPQQtKp7crzhyt2aVZB2M7JAGsJCr1TUZl9Y2KgAKkCQnpwBAZdntUB0DvodBFqVG61zaH4yY6k+5kiHC+kZ9gSqoh3gMoMlANRqaoIB+3IVf1TXWyVx4dp11RGCBxNmccvA1h+RsI8GXsCPSLYINiQLKWUl3jmNYbmQKK7TyWWl/soCTco6NnyivLp6cxbDi0zqy5xTDc=
  skip_cleanup: true
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  name: Travis "$TRAVIS_TAG"
  body: https://github.com/CyberMiles/travis/blob/develop/CHANGELOG.md#${TRAVIS_TAG//.}
  on:
    repo: CyberMiles/travis
    tags: true

after_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  - TAG=$TRAVIS_TAG make push_tag_image ;
