language: go

branches:
  only:
  - master
  - develop
  - tmup
  - lity

services:
  - docker

addons:
  hosts:
    - node-1
    - node-2
    - node-3
    - node-4
    - node-5
    - node-6

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

script:
  - BRANCH=$TRAVIS_BRANCH make docker_image && ./test/integration/test.sh

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      make push_image ;
    else
      BRANCH=$TRAVIS_BRANCH make push_branch_image ;
    fi
